stages:
  - test
  - deploy

variables:
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite

before_script:
  - apt-get update && apt-get install -y unzip
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - cp .env.example .env
  - chmod -R 777 storage bootstrap/cache
  - mkdir -p database && touch database/database.sqlite
  - composer install --no-interaction --no-progress --prefer-dist
  - php artisan key:generate

test:
  stage: test
  image: php:8.3
  services:
    - name: mysql:5.7
      alias: mysql
  script:
    - php artisan test

.deploy:
  stage: deploy
  only:
    - main
  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
      cd /var/www/JapanDigitalUniversitySchedule
      sudo docker compose down
      sudo git reset --hard
      sudo git pull
      sudo docker compose up -d --build
      sleep 1
      sudo docker exec jdu_app php artisan migrate
      sudo docker exec jdu_app php artisan optimize
      echo "Deploy Completed!"
      EOF

  dependencies:
    - test
